# Generated by Django 5.0.5 on 2024-09-09 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
